services:
  hello-world:
    restart: always
    depends_on:
      - database
    network_mode: host
  database:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:alpine
    network_mode: host